replicaCount: 1

image:
  registry: quay.io
  repository: uirlis/wasi-crun-deployer
  tag: v0.0.2
  pullPolicy: Always

job:
  name: "wasi-crun-deployer"
  label: "wasi-crun-job"
  vendor: "ubuntu_18_04"
  libLocation: "/lib"
  logLevel: "info"
  ociLocation: "/usr/local/sbin"
  configLocation: "/etc/containerd"
  ociName: "crun"
  nodeRoot: "/mnt/node-root"
  isMicroK8s: false
  autoRestart: true

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: "wasi-crun-admin"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}

scc:
  create: false
